name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  # ── Backend ────────────────────────────────────────────────────────────────
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Build Backend
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .